archlinux/archweb

- news/migrations/0002_news_send_announce.py
- news/models.py
- news/views.py
- templates/news/news_email_notification.txt
Send an e-mail to arch-announce when a new news is added to the database.
> News2email

- releng/models.py
- releng/views.py
> Use x86_64 instead of dual postfix for ISO image names

- templates/public/download.html
Signed-off-by: Jelle van der Waa <jelle@vdwaa.nl>
> Use code tags instead of backticks

- README.md
An test setup SMTP server can be used to test actions which require a
mail to be sent, for example user creation.
> Describe the setup steps for a debug SMTP server

- devel/forms.py
- devel/management/commands/pgp_import.py
- devel/management/commands/rematch_developers.py
- devel/reports.py
Archweb has a lot of pylint warnings, eventually it would be nice to run this for every PR. So I've started fixed the low-hanging fruit.
> Fix a couple of pylint warnings

- .travis.yml
- README.md
Describe the running of the unit tests and generating coverage. Coverage is currently at 37%.
> README: describe running unit tests / coverage

- templates/public/download.html
Code tags should be closed with a </close> tag
Signed-off-by: Jelle van der Waa <jelle@vdwaa.nl>
> Fix invalid code tags

- mirrors/tests.py
Add a simple /mirrors/status test.
\o/ more tests 👍
> mirrors: add simple test for mirror stats

- settings.py
Fixes the ability to get nice context by a broken template :)
> Debug template

- README.md
Describe how to import the package file listing for the listing in
/packages/$repo/$arch/$pkgname/files and on
/packages/$repo/$arch/$pkgname.
> README: describe importing the package file listing

- sitestatic/archweb.css
Signed-off-by: Christian Hesse <mail@eworm.de>
> dev dashboard: highlight table rows on mouse hover

- devel/templatetags/group.py
- templates/base.html
Hide the arch-dev mailing list archives for non developers. (We don't want to make the secret sauce obvious ;-) )
> Filter arch-dev mailing list for non-devs

- devel/tests.py
- devel/views.py
Since Django 1.8 each_context requires a request argument.
> devel: fix /devel/admin_log

- main/templatetags/details_link.py
- templates/packages/package_details.html
Show a link for security issues on the package details link.
> Add a security link to package details

- templates/packages/details_relatedto.html
Remove the extranous space in Provides / Conflicts by removing the
newline in details_link.html with spaceless
> packages: remove extranous space in Provides/Conflicts

- .pylintrc
- .travis.yml
- devel/forms.py
- main/models.py
- mirrors/tests.py
- packages/templatetags/package_extras.py
- packages/tests.py
- packages/views/__init__.py
- public/utils.py
- public/views.py
- releng/models.py
- releng/tests.py
- releng/views.py
- urls.py
This is a lot of cleanups, mostly due to the issues found by pylint and two deprecation fixes.
> Refactor and introduce Pylint to travisci

- packages/tests.py
Test all known scenario's and easy to test search scenario's.
> packages: Add tests for json and normal package search

- packages/tests.py
Add additional tests for our opensearch endpoints
> Add opensearch tests

- mirrors/tests.py
- packages/tests.py
Add more tests for basic urls in preparation of the django 1.11 upgrade.
> Add more basic url tests

- devel/tests/test_reports.py
- main/management/commands/donor_import.py
- main/tests/test_donor_import.py
- main/tests/test_templatetags_pgp.py
- mirrors/tests/test_mirrorlist.py
- mirrors/tests/test_mirrors.py
- mirrors/tests/test_mirrorstatus.py
- todolists/tests/test_templatetags_todolists.py
- todolists/tests/test_views.py
Add / extend some new tests to further improve coverage and maybe even uncover bugs in the django upgrade branch.
> Extended tests

- requirements.txt
This django release contains two small bugfixes.
> Update django to 1.11.12

- sitestatic/archweb.css
Clean up leftover releng css and remove weird css rule.
> Clean up CSS

- requirements.txt
Minor bugfix release which fixes two regressions and one crash.
> requirements: Update django to 1.11.13

- mirrors/tests/test_mirrorlocations.py
- mirrors/tests/test_mirrors.py
- mirrors/tests/test_mirrorstatus.py
- packages/tests.py
- releng/tests/test_views.py
Instead of importing json and loading the response.content using
json.loads use Django's response.json() method.
> test: use response.json()

- devel/tests/test_rematch_developers.py
- main/utils.py
- mirrors/tests/test_mirrorlist.py
- packages/tests.py
- packages/utils.py
- packages/views/__init__.py
- todolists/tests/test_views.py
Extend our packages/todolist tests.
> Tests extended

- devel/views.py
- main/templatetags/pgp.py
- mirrors/views/__init__.py
- mirrors/views/api.py
- packages/views/flag.py
- packages/views/search.py
- settings.py
Fix Django deprecations so updating to 2.x is easier.
> Django deprecations

- sitestatic/archweb.js
- templates/packages/differences.html
- visualize/static/visualize.js
Fix jQuery deprecation's, remove unused JavaScript and move JavaScript to only used page.
> Js deprecated

- devel/management/commands/reporead.py
> reporead: Delete old FlagRequests when deleting package from repo

- templates/packages/package_details.html
> Hide unflag all split packages for non-split packages

- packages/management/commands/populate_signoffs.py
When populating new signoffs also clean up old signoff's and
signoffspecifcations by querying the database for everything which is
not displayed on the website.
> populate_signoffs: clean up old signoff(specifications)

- devel/reports.py
Add a new devel report which shows packages which have non-existing
make, opt or normal dependencies.
> devel: add non existing dependencies report

- packages/views/signoff.py
- templates/packages/approved.txt
> Send notification once package has enough signoffs

- templates/public/about.html
fairly sure this shouldn't be there :P
> about: Remove superfluous comma

- .github/workflows/main.yml
Signed-off-by: Jelle van der Waa <jelle@archlinux.org>
> Add github actions workfow

- packages/views/search.py
Signed-off-by: Johannes Löthberg <johannes@kyriasis.com>
> Add support for searching by package provides

- .gitlab-ci.yml
Signed-off-by: Jelle van der Waa <jelle@archlinux.org>
> Add gitlab CI integration

- main/templatetags/details_link.py
- templates/base.html
- templates/packages/package_details.html
I did not actually test how it looks, hope it's all right!
> Add link to manpages from Package Actions

- settings.py
> Fix warnings related to missing default_auto_field

- conftest.py
- feeds.py
- planet/tests/test_views.py
Add author name to planet feed (as suggested by https://github.com/archlinux/archweb/issues/377).
> Add author to planet feed

- devel/management/commands/archweb_inotify.py
- devel/management/commands/generate_keyring.py
- devel/management/commands/pgp_import.py
- devel/management/commands/read_rebuilderd_status.py
- devel/management/commands/readlinks.py
- devel/management/commands/readlinks_inotify.py
- devel/management/commands/rematch_developers.py
- devel/management/commands/reporead.py
- devel/management/commands/reporead_inotify.py
- devel/management/commands/retire_user.py
- main/management/commands/donor_import.py
- mirrors/management/commands/mirrorcheck.py
- mirrors/management/commands/mirrorresolv.py
- packages/management/commands/populate_signoffs.py
- planet/management/commands/update_planet.py
- settings.py
This is a proposition for a single management command logger configuration as suggested by https://github.com/archlinux/archweb/issues/209.
> Mutualize commands logger configs

- templates/packages/removed.html
- templates/packages/search.html
- templates/public/feeds.html
https://github.com/archlinux/archweb/issues/401
> remove aur.archlinux.org .php extension usage

- templates/base.html
- templates/packages/flag.html
- templates/packages/flaghelp.html
- templates/public/download.html
- templates/public/index.html
Link to the mailman3 interface.
See https://gitlab.archlinux.org/archlinux/infrastructure/-/issues/59
CC @klausenbusk
> Update (mailman|lists).archlinux.org links

- main/context_processors.py
- settings.py
- templates/public/index.html
Signed-off-by: Morten Linderud <morten@linderud.pw>
> index: add support for MASTODON_LINK

- mirrors/tests/conftest.py
- mirrors/tests/test_mirrors.py
- mirrors/views/api.py
Add the tier / upstream mirror information.
Closes #452
> mirrors: extend /mirrors/xyz/json/ endpoint

- templates/devel/tier0_mirror.html
> devel: fix grammar mistake a HTTP => an HTTP

- templates/public/download.html
> public: update to latest seqouia version

- devel/management/commands/readlinks_inotify.py
- devel/management/commands/reporead_inotify.py
- mirrors/management/commands/mirrorcheck.py
i tested this solution, seems to work quite well
> set a timeout for the rsync subprocess when checking mirror availability

- templates/public/download.html
https://geo.mirror.pkgbuild.com/wsl/latest
https://gitlab.archlinux.org/archlinux/archlinux-wsl/
> Add WSL images to the download page

- templates/public/download.html
More informative than the GitLab repo's README
> Point to the wiki page in the WSL images download section

- devel/migrations/0011_userprofile_social.py
- devel/models.py
- templates/public/developer_list.html
This is a follow up to https://github.com/archlinux/archweb/pull/552
I've went through README.md and nothing failed but there doesn't seem to be any fixtures regarding users.
I'm no Python/Django dev so any help would be very appreciated :sweat_smile:
> Add `social` field to user's profiles

- sitestatic/archweb.js
- templates/packages/signoffs.html
Implements https://github.com/archlinux/archweb/issues/550
> signoffs: add "Only Mine" filter
