archlinux/archweb

templates/releng/archlinux.ipxe
Since this script sets 'ip=dhcp' by default, archiso_pxe_common will fail if more than one network interface exists, and at least one interface cannot be configured by dhcp. Setting BOOTIF will define which interface that archiso_pxe_common should configure, and will cause it to ignore the rest.
Fixes https://bugs.archlinux.org/task/50448
=> Define BOOTIF in extrabootoptions

templates/mirrors/status_table.html
The filter was passed an undefined variable which caused the template to
be rendered as empty. Since the other table columns default to an empty
string instead of "unknown", simply remove the default:"unknown" filter.
Also correct a closing %} tag.
=> Remove invalid filter call from mirrors/status_table.html

packages/migrations/0003_auto_20170524_0704.py, releng/migrations/0004_auto_20170524_0704.py, releng/models.py
Fixes warnings for releng.Test.modules and releng.Test.rollback_modules
(fields.W340) null has no effect on ManyToManyField.
=> releng: Fix django warnings

main/templatetags/pgp.py
The autoescape option is always true in our codebase so remove the
unused non escaping option.
=> main: Clean up unused option in pgp_fingerprint

settings.py
Remove double #'s everywhere, remove spaces between [], place : directly
after the string and correctly indent the TEMPLATES declaration.
Some day everything will be flake8 complaint =)
=> settings.py: handle flake8 warnings

.coveragerc, .travis.yml, main/fixtures/package.json, mirrors/tests.py, news/tests.py, packages/tests.py, public/tests.py, releng/fixtures/release.json, releng/tests.py, visualize/tests.py
Create a coveragerc file, fix a faulty test, completely test visualize/*. Add missing feed and url tests.
=> Tests add 12% more coverage

public/tests.py, urls.py
The legacy urls where introduced in 2011 get rid of them since it's
2017.
=> urls.py: remove legacy urls

devel/views.py
Since we have testers and other kind of users, filter the users that
appear on the devel clocks page for membership on Developers, Trusted Users
or Support Staff only.
=> Filter the users that appear on the devel clocks page

sitestatic/archnavbar/archnavbar.css, sitestatic/archweb.css
Previously, all of these links would drop beneath the header,
making the navigation difficult to use, as it would become white
links on an off-white background.
=> Change navbar css so that links wrap in header on narrow windows

sitestatic/archweb.css
Reverts archlinux/archweb#37 (to address the "Developer Dashboard" becoming yellow).
=> Revert "dev dashboard: highlight table rows on mouse hover"

sitestatic/archweb.css
Commit 73c6ac09ae3080791219b3b3bb31cffb20b82e53 ("dev dashboard: highlight
table rows on mouse hover") colored the complete dev dashboard in yellow,
this was reverted by d4cd8a2396a475f08ddc6aff2f8ecd4caca8c313 ("Revert
"dev dashboard: highlight table rows on mouse hover"").
Try again with fixed CSS.
=> dev dashboard: highlight table rows on mouse hover, second try

public/views.py
> Passing callable arguments to queryset is deprecated.
=> Fix RemovedInDjango19Warning

local_settings.py.example, main/templatetags/cdn.py
Remove the unused CDN configuration option for JQuery.
Signed-off-by: Jelle van der Waa <jelle@vdwaa.nl>
=> Remove CDN configuration option

templates/packages/package_details.html
Hide the adopt button when the user is unable to adopt the packages
since it's not in his allowed repos
=> Hide adopt button if user can not adopt it

templates/public/index.html
This PR fixes https://bugs.archlinux.org/task/55435 and updates all links on index.html to HTTPS.
=> Remove schwag

packages/admin.py
Django 1.7 changed the method name to get_queryset.
=> packages/admin: Fix the syntax for queryset

main/fixtures/package.json
Low hanging fruit, we should also fix the fixtures mentioning i686.
=> Update test to x86_64

main/templatetags/details_link.py
This completely screws up searching for bugs, as you can easily miss any
bugs filed to the testing package, and will *always* miss the ones that
have been moved to "Upstream Bugs".
There is no purpose in restricting the view of bugs filed against a
specific package, to some arbitrary subcategory of "why" the bug was
filed; all it accomplishes is causing unknowing users to file duplicate
bug reports.
=> package details: remove category from bugtracker links

packages/utils.py
Currently all dependencies are under the same `depends` key in the JSON results.  With this commit they're instead sorted under keys for each dependency type instead.
=> Return different dep types under different keys in JSON results

mirrors/views/api.py
(Of course I catch this *after* it's already been deployed, but at least it doesn't break anything that already worked.)
=> mirrors/views/api: Fix mirrors.change_mirror perm typo

main/management/commands/donor_import.py, main/tests/test_donor_import.py, requirements.txt
This script imports messages from a Maildir folder and creates new
unique Donors based on the name in the subject. The subject also
contains the amount and the email address, which is not stored by
Archweb.
The input has to stripped quiet a bit, some entries are fully capitalised for example:
Receipt [$25.00] By: JOHN DOE [john.doe@archlinux.org]
Or contain extra numbers:
Receipt [$25.00] By: JOHN DOE 234234324 [john.doe@archlinux.org]
Or contain no name at all:
Receipt [$25.00] By: - - [john.doe@archlinux.org]
I've skipped / edited these entries
=> Add donation import management script

templates/public/index.html
Include a link to the HELLOTUX t-shirt store, which donates $2 per
bought t-shirt to Arch Linux.
=> FS#51458: Add HELLOTUX to the support section

mirrors/views/api.py
Add the ipv4/ipv6 availability to the /mirrors/status/json api.
See https://bugs.archlinux.org/task/50516
=> FS#50516: mirrors: Extend /mirrors/status/json/

devel/models.py
Due to changes to Django 1.11, this didn't return the object. Fix to get the object instead
of the queryset.
=> Fix the StaffGroup query

templates/public/download.html
Mention the official Vagrant image on the download page and where to
find it.
This PR needs a rebase first.
=> public: Add vagrant image link to download page

README.md, feeds.py, packages/models.py, templates/public/feeds.html, urls.py
This PR adds two feeds, one for newly added packages (which did not exists in the repo before) and removed packages. This requires triggers to be configured in your database for updates. For SQLite they are not setup for some reason by default? Is it possible we can make this happen? @angvp @grazzolini? Then we can at least right some tests.
The triggers can be found in packages/sql. packages/sql/update.sqlite3.sql for sqlite and packages/sql/update.postgresql_psycopg2.sql for PostgreSQL which seems to be enabled and working in production! 👍
=> Added removed rss

todolists/tests/test_views.py, todolists/urls.py, todolists/views.py
Add a /todo/$name/json endpoint which returns the json for a todo list
item.
=> todolists: Add json endpoint for todo detail view

devel/management/commands/reporead.py, devel/tests/test_reporead.py
When updating a package in our repository remove any old 'flagged out of
date' requests.
=> devel: reporead remove old flagrequests

README.md
The old is obsolete and migrated to travis-ci.com
=> readme: replace build status badge with new travis-ci.com

todolists/models.py, todolists/urls.py, todolists/views.py
Old todolist items contained an old_id to keep links working, these
items where most recenlty created 6 years ago. Since old todolists of a
long time ago aren't particularly interesting they will be removed.
Closes #141
=> todolists: remove old_id from todolist model

templates/news/paginator.html, templates/packages/search_paginator.html
Add the “rel” attribute for “prev” and “next” to the pagination links
of news and packages.
=> Add “rel” attribute to pagination links

devel/models.py, main/models.py, mirrors/models.py, packages/models.py, todolists/models.py
Foreignkey used to implicitly be on_delete=models.CASCADE and has to be
explicit now.
=> Fix Foreignkey implicit on_delete on django < 2.0

templates/public/about.html
The [unsupported] section blurb was outdated in both its existence and
the fact that there are almost 50k PKGBUILDs inside of it as of $DATE.
=> templates/public/about: remove unsupported section

devel/management/commands/pgp_import.py, devel/tests/test_pgp_import.py, main/models.py, main/utils.py
We use the attribute in many places, but it's a "bytes" object in
pgpdump that messes up the remaining logic. Let's just wrap it from the
very beginning.
=> Make Package.signature return str key_id

settings.py
The MIT keyserver is very unstable and slow during the past years. I would suggest to use a better alternative.
=> Use sks-keyservers instead of mit

main/models.py
Since there are multiple [testing] repositories when a package is in
kde-unstable, testing and flagged in extra the in_testing function will
generate an error since there are multiple results. Rewrite the query so
it handles multiple results and order it by id since [testing] should
have a lower id then kde-unstable.
=> main: Handle multiple testing repositories

templates/todolists/complete_email_notification.txt, todolists/models.py
When a todolist item is complete ie. all TodoListPackages belonging to
the todolist are marked as COMPLETE inform the creator of the todolist
via an email.
Closes: #222
Signed-off-by: Jelle van der Waa <jelle@vdwaa.nl>
=> todolist: send email when the todolist is fully complete

devel/management/commands/reporead.py
Needed for clearing out [kde-unstable].
=> reporead: skip sanity check for public testing repos

packages/views/search.py
Resolve 500 issues when limit=wji or limit=-1 by setting a min_value of
0 and changing the field to a IntegerField.
=> packages: fix negative and invalid limit in search API

local_settings.py.example
When I started developing archweb locally today, I couldn't log in due to missing CSRF cookie. It turns out that `settings.CSRF_COOKIE_SECURE` (which works like `SESSION_COOKIE_SECURE`) needs to be `False` when accessing the site via plaintext HTTP.
Hope this patch could get future contributors started a little easier.
=> Developing locally needs CSRF_COOKIE_SECURE=False

requirements.txt, settings.py
Django extensions comes with a lot of goodies, including shell_plus. As a default,
included ptpython for default shell, but this can be overridden by installing another
shell (bpython, ipython) and setting the SHELL_PLUS variable on local_settings.py.
=> Add django-extensions to the default installation

templates/public/download.html
We have an official docker image now, let's mention that on our
`Download` page.
Signed-off-by: Christian Rebischke <chris@nullday.de>
=> Add information about official docker image

news/views.py, settings.py
Given that the whitelisting of the arch-announce email is not sufficient for validation, we are setting a poster password to make sure the list cannot be abused.
=> news: Add the MAILMAN_PASSWORD option and use it for sending authenticated emails

main/templatetags/details_link.py
Git log operations on the master branch take too long to finish and the
history pages on GitHub time out because of this. Switch to using the
package branches similar to how it was done when svntogit was on cgit.
Fixes: https://github.com/archlinux/archweb/issues/290
=> Include package branch in svntogit links

templates/releng/archlinux.ipxe
templates/releng/archlinux.ipxe:
Fix the naming of the initrd images.
In a commit leading to archiso 46 [1] (image 2020-08-01) the way files
are being copied in the build script has been made more generic. Due to
this change the names of the provided PXE netboot images on the download
servers have changed as well and stopped matching the files as provided
in archweb's .ipxe template.
Add amd-ucode.img as additional initird to be downloaded, verified and
used.
[1] https://gitlab.archlinux.org/archlinux/archiso/-/commit/47e11125e4672fc3448caefa6728439160daedd3
=> Fix PXE netboot image names

templates/releng/archlinux.ipxe
templates/releng/archlinux.ipxe:
It seems that two copy/paste errors were introduced in the last pull
request [1] evolving around the renaming of initrd image names, which is
relevant for PXE netboot as well.
[1] https://github.com/archlinux/archweb/pull/294
=> Fix PXE netboot image names (for real)

mirrors/utils.py
Firefox Nighly does not popup the download dialog anymore as it might be
blocking opening http:// links from a https:// origin. Bug reported in
https://bugs.archlinux.org/task/67587
=> Use https mirrors for downloading packages

sitestatic/archweb.css
The latest news entry ([Kill Arch Bugs: Help us on the 13th of September!](https://www.archlinux.org/news/kill-arch-bugs-help-us-on-the-13th-of-september/)) contains `h3` headings, which are rendered incorrectly on the main archlinux.org page - they are left-floated and too big and outside of the hierarchy (the "Latest News" is `h3` and the titles of the news are `h4`, so headings inside the news should be `h5` or `h6`). This commit fixes the visual problem by styling all headings inside the news previews to look the same as `h5`.
=> Fix rendering of headings inside news previews

templates/releng/archlinux.ipxe
templates/releng/archlinux.ipxe:
With https://gitlab.archlinux.org/archlinux/archiso/-/merge_requests/74
the naming scheme of the initramfs is not hardcoded (i.e. archiso.img)
anymore but follows the standard naming scheme (i.e. initramfs-linux.img
when using the standard linux kernel package).
NOTE: This can only be merged and made available *after* the image for
October 2020 (e.g. 2020-10-01) has been made available.
=> Rename initramfs file

devel/management/commands/reporead.py, requirements.txt
As Python does not support zstd compression yet, xtarfile a wrapper
around tarfile with zstd support is required.
=> Add core.db.tar.zst support for reporead

packages/utils.py, todolists/models.py, todolists/views.py
Include the status of a todolist package as a string, so the json output
can be used to determine the completeness or the packages left to
rebuild.
=> Add complete status to the todolist json endpoint

planet/management/commands/update_planet.py, planet/tests/test_command.py
When a 301 is returned the callee is expected to update it's database
entry to reflect this change. As subsequent returning requests to the
old url might lead to ip bans.
=> Handle 301 when updating planet feeds

README.md, main/management/commands/donor_import.py, main/tests/test_donor_import.py
While the approach to iterate on a maildir works fine, this needs
additional tooling. Taking an email on stdin allows to set the script as
mda command in e.g. fetchmail and process the mail on delivery without
storing it to a maildir.
=> alter donor_import.py to work as mda command

main/models.py, sitestatic/archweb.css, templates/packages/package_details.html
This PR adds an extra green text line with "X minutes ago" to recently upgraded packages, next to the update date. This is to notify people that a given version might not yet be synchronized on various mirrors. Looks like this:
=> Notify about recently updated packages

sitestatic/archweb.css, templates/packages/flag.html
Displays a red bar with a warning message that a given package was updated relatively recently and might not yet be available on all mirrors. It's intentionally designed to look a bit obnoxious so that people hopefully read the message before flagging.
Looks like so (message in the bar now displays the pkgver, ex. 5.8.0, not the full_version, ex. 5.8.0-2):
=> Warn users trying to flag recently updated pkgs

templates/public/index.html
Add a link to the sidebar on the front page. (This could also be linked in the global navbar, IMO.)
=> Link man.archlinux.org on the front page

main/templatetags/details_link.py, templates/base.html, templates/mirrors/mirrorlist_generate.html, templates/public/art.html, templates/public/download.html, templates/public/index.html, templates/public/svn.html, templates/releng/netboot.html
Done with: find -type f -exec sed -Ee ':wiki.archlinux.org: s:(wiki.archlinux.org)/index.php/:\1/title/:g' -i {} \;
Fix #343
[1] https://gitlab.archlinux.org/archlinux/infrastructure/-/merge_requests/335
=> Update wiki links to the new short URL

settings.py
All the arch-x@archlinux.org -> arch-x@lists.archlinux.org aliases will
be dropped soon[1].
[1] https://lists.archlinux.org/pipermail/arch-dev-public/2021-June/030462.html
=> Update mailing list address

devel/views.py
Commit e4b211e8 (Allow users to set their own names, 2021-10-14) tried
to allow users to set their own names.  It correctly handles the latin
name field, but it doesn't end up actually saving changes to the first
and last name fields.
Signed-off-by: Johannes Löthberg <johannes@kyriasis.com>
=> devel/views: Actually save first and last names when they change

templates/base.html
Add theme-color meta tag to header using archlinux-blue color (https://developer.mozilla.org/docs/Web/HTML/Element/meta/name/theme-color).
=> Add theme-color meta tag

releng/views.py, templates/releng/netboot.html
This should resolve #364. Extended netboot_info to get ipxe package and pass along to netboot template.
=> Extended netboot_info + replaced hardcoded url

requirements.txt
The unauthenticated `git://` protocol has been disable on GitHub[^1] and we
need to use `https://` or `git@github.com:<user>/<repo>` to pull a repository.
[^1]: https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Fix pip install error

templates/packages/package_details.html
Currently we link to `https://archlinux.org/packages/core/any/base/download` which redirects again before redirecting to a mirror. It's likely an nginx rule somewhere, adding this slash to the link makes the download _slightly faster_.
```
% curl -I 'https://archlinux.org/packages/core/any/base/download'
HTTP/2 301 
server: nginx
date: Wed, 03 Aug 2022 11:35:19 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: /packages/core/any/base/download/
x-cache-status: MISS
strict-transport-security: max-age=31536000; includeSubdomains; preload
```
```
% curl -I 'https://archlinux.org/packages/core/any/base/download/'
HTTP/2 302 
server: nginx
date: Wed, 03 Aug 2022 11:35:38 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: …
```
=> Change the `Download From Mirror` link to skip one redirect

templates/devel/index.html, templates/todolists/list.html
With long descriptions the todolist overview table gets unwieldy. The
todo title should suffice for these views, and the description should
only be shown in the todo details page.
=> Leave descriptions out of todolist overview tables

releng/models.py, templates/public/download.html
Previosly it was not linked from anywhere, making one think that it can only be downloaded from the mirrors which is not safe.
=> Add bootstrap tarball PGP signature to the downloads page

sitestatic/archweb.css
`1.2em monospace` is slightly smaller than 1em of any other text.
Use `monospace, monospace` as the font to workaround the browser quirk instead of explicitly setting the font size.
=> Make monospaced text the same size as the rest of the text

templates/public/download.html, templates/releng/release_list.html
* Some BitTorrent clients need additional configuration to enable DHT. See https://bugs.archlinux.org/task/71368 and https://bbs.archlinux.org/viewtopic.php?pid=1982176#p1982176.
* Mention WebSeeds instead of the decomissioned torrent tracker in releng release list
=> Note the requirement of DHT for BitTorrent downloads

templates/public/download.html
Link to https://wiki.archlinux.org/title/USB_flash_installation_medium instead of vaguely mentioning that `dd` can be used.
=> Link to "USB flash installation medium" on the wiki for instructions on preparing a USB flash drive

templates/todolists/list.html
After removing the description column, status has become the 7th column
instead of the 8th; fix the tablesorter call to use the correct number.
Fixes: 74e24ff4e6a9 ("Leave descriptions out of todolist overview tables")
=> todolists: restore ordering by status in list view

templates/releng/archlinux.ipxe
See https://gitlab.archlinux.org/mkinitcpio/mkinitcpio-archiso/-/merge_requests/24 for details.
After there have been at least three releases with OpenSSL signed netboot artifacts, the GPG-based verification option `verify=y` can be removed.
/cc @dvzrv @Torxed
=> archlinux.ipxe: Turn on OpenSSL CMS signature varification for root file system

templates/releng/archlinux.ipxe
Now that there have been three ISO releases with OpenSSL signed root file system image, the GPG-based verification option `verify=y` can be removed.
Doing this will allow releasing official ISOs without a GPG signed root file system image. The past few ISOs have been signed with an "Ephemeral Signing Key", so nothing of value will be lost.
This was done because it is complicated to run `mkarchiso` as root while passing it the user's GPG keys.
The envisioned future automated release process would also benefit by not tangling itself with GPG and only rely on code signing certificates.
Follow-up to commit 248908d4223b9ccf274fe19175b91d365a8501f8
/cc @dvzrv @Torxed
=> archlinux.ipxe: do not perform GPG signature verification for the root file system image

templates/packages/search.html
This make it clear for those people who are curious about why the version text is in red.
=> Add 'out-of-date' title to flagged packages in search page

README.md
Python's [smtpd](https://docs.python.org/3/library/smtpd.html) will be deprecated in python 3.12. This commit updates archweb's README to include instructions for using
[aiosmtpd](https://aiosmtpd.readthedocs.io/en/latest/cli.html) instead, as recommended by the deprecation notice on python.org.
Fixes https://github.com/archlinux/archweb/issues/453
=> Update README for deprecated smtpd with aiosmtpd.

templates/public/download.html
There are two outdated links on the download page:
- link to the releng/iso bugtracker
- link to the built vm images
fixes https://bugs.archlinux.org/task/79331
fixes https://bugs.archlinux.org/task/78321
=> template: update outdated links on the download page

packages/urls.py, packages/views/__init__.py
For our Gitlab bot to assign members automatically to packaging repository a mapping is needed of pkgbase to maintainers.
=> packages: supply a pkgbase/maintainer mapping

templates/base.html, templates/public/art.html
Arch Linux trademark policy was moved from ArchWiki to https://terms.archlinux.org/
Related to https://gitlab.archlinux.org/archlinux/service-agreements/-/issues/5
/cc @christian-heusel
=> templates: update trademark policy URL

devel/fixtures/staff_groups.json, devel/management/commands/retire_user.py, devel/views.py, docs/mirror_access.md, main/fixtures/groups.json, sitestatic/archweb.css, templates/base.html, templates/devel/profile.html, templates/planet/index.html, templates/public/keys.html
In the continuity of the effort started to apply the 'TU --> Package Maintainer' rename to every Arch ressources, here's a PR for archweb :)
Related MRs/Tickets:
- https://gitlab.archlinux.org/archlinux/package-maintainer-bylaws/-/merge_requests/6
- https://gitlab.archlinux.org/archlinux/aurweb/-/merge_requests/755
- https://gitlab.archlinux.org/archlinux/infrastructure/-/issues/533
This PR also updates the few obselete mentions to the [community] repository in the various descriptions
=> Rename TU to Package Maintainer

packages/tests/test_search.py, packages/tests/test_views.py
Due to a Django bug or pytest-django-test bug the tests currently do not succeed. Drop them for now until they work.
=> packages: tests: drop client.head tests

main/templatetags/details_link.py, templates/base.html, templates/public/feeds.html
Our old flyspray bugtracker is deprecated and we migrated to Gitlab where now all packaging and project issues should be created. As it doesn't make a lot of sense to keep bugs in the header update it to Gitlab.
=> Switch bugs.archlinux.org to Gitlab

templates/public/download.html
Starting with archlinux-2024.02.01-x86_64.iso, the ISO size will exceed the maximum CD size (900 MiB).
Adjust the text to say "DVD" instead.
Related to https://gitlab.archlinux.org/archlinux/archiso/-/issues/144
/cc @dvzrv
=> templates/public/download.html: replace "CD" with "DVD"

public/views.py
This issue was raised in #archlinux-security, and I also think listing https only mirrors on archlinux.org/download/ is a good idea.
Or put differently, I don't think insecure http is relevant enough anymore to list them on the download page.
=> When linking iso downloads, only use https mirrors

templates/public/download.html
sequoia-sq 0.33 has changed the `sq wkd get` command with `sq network wkd fetch`
=> template: changed signing key download command for sq >= 0.33

releng/models.py, templates/public/download.html
Link to *sum.txt files on archlinux.org, just like with the GPG signatures, as the mirrors cannot be trusted.
Add the GnuPG verification command from https://wiki.archlinux.org/title/Installation_guide#Verify_signature. It would be better if we do not duplicate it in both archweb and the wiki.
=> templates/public/download.html: update checksum and signature list and verification

templates/packages/flaghelp.html
Now that the bugtracker has been moved to GitLab, the flaghelp text should match.
=> Update flaghelp.html with link to GitLab

devel/models.py
Testers could add a blog and have it post to planet, this does not represent Arch's Staff.
=> devel: only allow adding a blog to planet for staff

templates/public/download.html
Reported in https://bbs.archlinux.org/viewtopic.php?id=295151
Fixes: b018f09fcada5a3b71d9b91bacfd1ddee9af9952 ("templates/public/download.html: update checksum and signature list and verification")
=> templates/public/download.html: fix mismatched closing tag

templates/releng/archlinux.ipxe
archlinux-2024.05.01-x86_64.iso made with archiso v77 will not contain external ucode images anymore. They will be part of the single initramfs file. See https://gitlab.archlinux.org/archlinux/archiso/-/merge_requests/370
Related to https://gitlab.archlinux.org/archlinux/archiso/-/issues/226
/cc @dvzrv
=> templates/releng/archlinux.ipxe: remove references to external ucode images

templates/base.html
=> templates/base.html: close meta tag

releng/models.py
archiso v77 changed the bootstrap tarball compression from gzip to zstd. See https://gitlab.archlinux.org/archlinux/archiso/-/merge_requests/373
Related to https://gitlab.archlinux.org/archlinux/archiso/-/issues/130
/cc @dvzrv
=> releng/models.py: update bootstrap tarball extension

templates/public/download.html
Fix list items so that the closing li tag is properly recognized.
Fixes: b018f09fcada5a3b71d9b91bacfd1ddee9af9952 ("templates/public/download.html: update checksum and signature list and verification")
The `<p>` element cannot contain `<pre>` elements.
Fixes: b018f09fcada5a3b71d9b91bacfd1ddee9af9952 ("templates/public/download.html: update checksum and signature list and verification")
=> templates/public/download.html: fix HTML

README.md
Fix the badge of the build status, see: https://github.com/shink/archweb/blob/docs/fix-badge/README.md
before:
[![Build Status](https://github.com/archlinux/archweb/workflows/Github-Actions/badge.svg)](https://github.com/archlinux/archweb/actions)
after:
[![Build Status](https://github.com/archlinux/archweb/actions/workflows/main.yml/badge.svg)](https://github.com/archlinux/archweb/actions/workflows/main.yml)
=> docs: fix the badge of the build status

mirrors/views/mirrorlist.py, planet/tests/test_command.py, releng/migrations/0001_squashed_0005_auto_20180616_0947.py, requirements.txt
Issues:
* The undocumented BaseForm._html_output() method is removed.
* Model instances passed to related filters must be saved.
=> Update to Django 5

sitestatic/archweb.css, templates/base.html
We can no longer logout with a GET and as folks probably don't want to depend on JavaScript for logging out, add a form and style the input as an anchor to make POST'ing work.
Closes: #511
=> devel: logout is a POST only action since Django 5.0

templates/public/download.html
indicate that download via HTTP is possible so that people new to arch dont get confused if they dont see the download from mirror option immediately
=> anchor to ISO download via mirrors right on top

settings.py, templates/devel/admin_log.html, templates/packages/package_details.html, templates/releng/release_detail.html
Explicitly specify the ISO 8601 format `Y-m-d H:i` in the date template.
Django 5.0.5 removed the `USE_L10N` setting making the locale-specific formats override `DATE_FORMAT` and `DATETIME_FORMAT`. See https://forum.djangoproject.com/t/datetime-format/30811/10 for details.
Fixes https://github.com/archlinux/archweb/issues/520
=> Use ISO 8601 date format

sitestatic/archweb.css, sitestatic/archweb.js
Currently, dynamic tables on archweb may look like this (a todo list with "Only Incomplete" checked; screenshot from a testing instance):
After this commit, it looks like a :zebra: again :smile:
=> Improve the "zebra" style of dynamic tables where rows can be dynamically hidden

packages/tests/test_search.py, packages/views/__init__.py, public/views.py
The domain came from HTTP_HOST which in our nginx configuration is not set, furthermore other code already uses Site to obtain the domain.
Closes: #541
=> Fix domain being None in opensearch results

templates/public/download.html
This automated `wsl --install archlinux` method will only be functional after https://github.com/microsoft/WSL/pull/12818 is merged, so we should wait for that before merging & deploying this PR (I'll remove the draft status once okay).
=> Add the automated install & run method for the WSL image to the Download page

requirements.txt
https://github.com/advisories/GHSA-wqfg-m96j-85vm (not that Windows matters much for running archweb, but still)
=> bump django to 5.0.14

templates/public/download.html
We are no longer releasing Vagrant images[1].
[1] https://gitlab.archlinux.org/archlinux/arch-boxes/-/commit/3f7b895725e9fa2f31436234a3b4a4e7f477f69d
=> public: Remove Vagrant images

templates/packages/differences.html
"x864_" is a typo of "x86_64".
https://archlinux.org/packages/differences
=> Fix typo on "Multilib Differences to Main Packages" page

templates/public/download.html
The public key is retrieved via WKD in the previous command, so there is no reason to contact any keyservers.
=> templates/public/download.html: remove gpg keyserver-options
